tasks:
  - init: |
      pip install --upgrade pip wheel setuptools poetry
      poetry install
      source .venv/bin/activate
      python manage.py migrate
    command: |
      source .venv/bin/activate
      python manage.py runserver

ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python