tasks:
  - init: |
      pip install --upgrade pip wheel setuptools poetry
      poetry install
      source .venv/bin/activate
      python manage.py migrate
      export DJANGO_SUPERUSER_PASSWORD=tcadmin
      python manage.py createsuperuser --username tcadmin --email tcadmin@fake.fake --no-input
    command: |
      source .venv/bin/activate
      python manage.py runserver

ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python